package Application.DAO;

import Application.Model.Author;
import Application.Util.ConnectionUtil;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * A DAO is a class that mediates the transformation of data between the format of objects in Java to rows in a
 * database. The methods here are mostly filled out, you will just need to add a SQL statement.
 *
 * We may assume that the database has already created a table named 'author'.
 * It contains similar values as the Author class:
 * id, which is of type int and is a primary key,
 * name, which is of type varchar(255).
 */
public class AuthorDAO {

    /**
     * Retrieve all authors from the Author table.
     * @return all Authors.
     */
    public List<Author> getAllAuthors() {
        List<Author> authors = new ArrayList<>();
        String sql = "SELECT * FROM Author";
        
        try (Connection connection = ConnectionUtil.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql);
             ResultSet rs = preparedStatement.executeQuery()) {
             
            while (rs.next()) {
                Author author = new Author(rs.getInt("id"), rs.getString("name"));
                authors.add(author);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return authors;
    }

    /**
     * Insert an author into the Author table.
     * The author_id should be automatically generated by the SQL database if it is not provided because it was
     * set to auto_increment. Therefore, you only need to insert a record with a single column (name).
     * @param author an author object.
     * @return The persisted author if the insertion is successful.
     */
    public Author insertAuthor(Author author) {
        String sql = "INSERT INTO Author (name) VALUES (?)";
        
        try (Connection connection = ConnectionUtil.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            preparedStatement.setString(1, author.getName());
            preparedStatement.executeUpdate();
            
            try (ResultSet pkeyResultSet = preparedStatement.getGeneratedKeys()) {
                if (pkeyResultSet.next()) {
                    int generated_author_id = (int) pkeyResultSet.getLong(1);
                    return new Author(generated_author_id, author.getName());
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return null;
    }
}

